ariston_iterative:
  pipeline:
    - preprocessing.binarization
    - preprocessing.edge_in
    - preprocessing.crop_to_contents
    - image.labeling
    - image.center_mean
    - image.extract_shapes
    - shapes.find_disc_edges
    - shapes.filter_inner
    - image.center_iterative
    - tracks.mean_shift
    - tracks.correct_empty
    - notes.create_notes
    - notes.find_beat_length
    - notes.create_midi
    - analysis.detect_key
  config:
    label_distance: 1
    inner_radius: 1.7
    outer_radius: 4.5
    # Average width of each track as relative distance between center and outer border
    track_width: 0.024 # Original value: 0.02267693
    first_track: 0.42
    n_tracks: 24
    bandwidth: 8
    bpm: 350 # Not actually bpm as we don't even know what a beat is...
    angle: 0.5
    iterations: 300
    track_mappings:
      1: 45
      2: 47
      3: 50
      4: 52
      5: 57
      6: 59
      7: 61
      8: 62
      9: 64
      10: 66
      11: 68
      12: 69
      13: 71
      14: 73
      15: 74
      16: 75
      17: 76
      18: 78
      19: 79
      20: 80
      21: 81
      22: 83
      23: 85
      24: 86
phonola_solodant:
  pipeline:
    - preprocessing.binarization
    - preprocessing.trim_roll_ends
    - preprocessing.edge_in
    - preprocessing.crop_to_contents
    - image.labeling
    - image.extract_shapes
    - image.find_roll_edges
    # - image.classify_shapes
    - image.filter_roll_shapes
    - image.extract_roll_notes
    - notes.scale_fixed_factor
    - notes.merge_roll_notes
    - notes.create_midi
  config:
    label_distance: 1
    width: 296
    bpm: 65
    scale_factor: 0.2
    # Just here till i fix the configuration validator
    track_mappings: []
    dpi: 300
    feet_per_minute: 6.5
    notes_per_second: 12
    bin_threshold: 60
    track_measurements:
      - left: 4
        right: 6.5
        tone: 29
      - left: 7.5
        right: 10
        tone: 31
      - left: 11
        right: 13.5
        tone: 32
      - left: 15
        right: 17.5
        tone: 33
      - left: 18.5
        right: 21
        tone: 34
      - left: 23
        right: 25.5
        tone: 35
      - left: 26.5
        right: 29
        tone: 36
      - left: 30
        right: 32.5
        tone: 37
      - left: 34
        right: 36.5
        tone: 38
      - left: 37.5
        right: 40.5
        tone: 39
      - left: 41.5
        right: 44
        tone: 40
      - left: 45
        right: 47.5
        tone: 41
      - left: 48.5
        right: 51.5
        tone: 42
      - left: 52.5
        right: 55
        tone: 43
      - left: 56
        right: 59
        tone: 44
      - left: 60
        right: 62.5
        tone: 45
      - left: 63.5
        right: 66.5
        tone: 46
      - left: 67.5
        right: 70
        tone: 47
      - left: 71
        right: 73.5
        tone: 48
      - left: 74.5
        right: 77.5
        tone: 49
      - left: 78.5
        right: 81
        tone: 50
      - left: 82
        right: 85
        tone: 51
      - left: 86
        right: 88.5
        tone: 52
      - left: 90
        right: 92.5
        tone: 53
      - left: 93.5
        right: 96
        tone: 54
      - left: 97.5
        right: 100
        tone: 55
      - left: 101
        right: 102.5
        tone: 56
      - left: 105
        right: 107.5
        tone: 57
      - left: 108.5
        right: 111
        tone: 58
      - left: 112
        right: 115
        tone: 59
      - left: 116
        right: 118.5
        tone: 60
      - left: 120
        right: 122.5
        tone: 61
      - left: 123.5
        right: 126.5
        tone: 62
      - left: 127.5
        right: 130
        tone: 63
      - left: 131.5
        right: 134
        tone: -1
      - left: 135
        right: 137.5
        tone: 64
      - left: 138.5
        right: 142.5
        tone: -1
      - left: 143.5
        right: 146
        tone: 65
      - left: 147
        right: 150
        tone: 30
      - left: 151
        right: 153.5
        tone: 66
      - left: 155
        right: 157.5
        tone: -1
      - left: 158.5
        right: 161
        tone: 67
      - left: 162.5
        right: 165
        tone: -1
      - left: 166
        right: 168.5
        tone: 68
      - left: 170
        right: 172.5
        tone: 69
      - left: 173.5
        right: 176.5
        tone: 70
      - left: 177.5
        right: 180
        tone: 71
      - left: 181
        right: 184
        tone: 72
      - left: 185
        right: 187.5
        tone: 73
      - left: 188.5
        right: 191
        tone: 74
      - left: 192
        right: 195
        tone: 75
      - left: 196.5
        right: 199
        tone: 76
      - left: 200
        right: 203
        tone: 77
      - left: 204
        right: 206.5
        tone: 78
      - left: 208
        right: 210.5
        tone: 79
      - left: 211.5
        right: 214
        tone: 80
      - left: 215.5
        right: 218
        tone: 81
      - left: 219
        right: 222
        tone: 82
      - left: 223
        right: 225.5
        tone: 83
      - left: 226.5
        right: 229.5
        tone: 84
      - left: 230.5
        right: 233
        tone: 85
      - left: 234
        right: 237
        tone: 86
      - left: 238
        right: 241
        tone: 87
      - left: 242
        right: 244.5
        tone: 88
      - left: 245.5
        right: 247.5
        tone: 89
      - left: 249.5
        right: 252
        tone: 90
      - left: 253
        right: 256
        tone: 91
      - left: 257
        right: 260
        tone: 92
      - left: 261
        right: 263.5
        tone: 93
      - left: 264.5
        right: 267.5
        tone: 94
      - left: 268.5
        right: 271
        tone: 95
      - left: 272
        right: 275
        tone: 96
      - left: 276
        right: 279
        tone: 97
      - left: 280
        right: 282.5
        tone: 98
      - left: 283.5
        right: 286.5
        tone: 99
      - left: 287.5
        right: 290
        tone: 100
      - left: 291
        right: 293
        tone: 101

        
          
        
      
ariston_lsq:
  pipeline:
    - preprocessing.binarization
    - preprocessing.edge_in
    - preprocessing.crop_to_contents
    - image.labeling
    - image.center_least_squares
    - image.extract_shapes
    - shapes.find_disc_edges
    - shapes.filter_inner
    - tracks.mean_shift
    - tracks.correct_empty_legacy
    - notes.create_notes
    - notes.create_midi
    - analysis.detect_key
    # - analysis.find_harmonies_bass
    # - analysis.find_harmonies_seq
    - analysis.plot_note_frequencies
    - analysis.find_last_chords
    - analysis.make_streamplot
  config:
    label_distance: 1
    inner_radius: 1.7
    outer_radius: 4.5
    # Average width of each track as relative distance between center and outer border
    track_width: 0.024 # Original value: 0.02267693
    first_track: 0.42
    n_tracks: 24
    bandwidth: 8
    bass_cutoff: 52
    cutoff: 59
    bin_threshold: 60
    lookahead: 5
    # Not actually bpm as we don't even know what a beat is...
    # Update: Maybe actually bpm now
    bpm: 90 
    track_mappings:
      1: 45
      2: 47
      3: 50
      4: 52
      5: 57
      6: 59
      7: 61
      8: 62
      9: 64
      10: 66
      11: 68
      12: 69
      13: 71
      14: 73
      15: 74
      16: 75
      17: 76
      18: 78
      19: 79
      20: 80
      21: 81
      22: 83
      23: 85
      24: 86
ariston:
  pipeline:
    - preprocessing.binarization
    - preprocessing.edge_in
    - preprocessing.crop_to_contents
    - image.labeling
    - image.center_mean
    - image.extract_shapes
    - shapes.find_disc_edges
    - shapes.filter_inner
    - tracks.mean_shift
    - tracks.correct_empty
    - notes.create_notes
    - notes.find_beat_length
    - notes.create_midi
    - analysis.detect_key
  config:
    label_distance: 1
    inner_radius: 1.7
    outer_radius: 4.5
    # Average width of each track as relative distance between center and outer border
    track_width: 0.024 # Original value: 0.02267693
    first_track: 0.42
    n_tracks: 24
    bandwidth: 8
    # Not actually bpm as we don't even know what a beat is...
    # Update: Maybe actually bpm now
    bpm: 90 
    track_mappings:
      1: 45
      2: 47
      3: 50
      4: 52
      5: 57
      6: 59
      7: 61
      8: 62
      9: 64
      10: 66
      11: 68
      12: 69
      13: 71
      14: 73
      15: 74
      16: 75
      17: 76
      18: 78
      19: 79
      20: 80
      21: 81
      22: 83
      23: 85
      24: 86


# Old format, needs to be converted as needed:

# mechanischer_vorsetzer:
#   punchholes: False
#   # Radius of the inner label, unit does not matter but has to match the one used for outer radius
#   inner_radius: 3.5
#   # Radius of the entire disc
#   outer_radius: 11.8
#   # Number of beats the disc has
#   number_beats: 144
#   # Bandwidth used for meanshift clustering the tracks
#   bandwidth: 8
#   # How far to look around each pixel when finding connected components in the image
#   search_distance: 1
#   # Average width of each track as relative distance between center and outer border
#   track_width: 0.01845976
#   # Relative position of the innnermost track from center to outer border
#   first_track: 0.325
#   # Total number of tracks on the disc
#   n_tracks: 36
#   # Low threshold for canny algorithm
#   canny_low: 100
#   # High threshold
#   canny_high: 255
#   # Preprocessing parameters
#   thresh_binary: 245
#   erosion_kernel: 3
#   noise_kernel: 5
#   brightness: 100
#   # Mappings of tracks to midi codes
#   track_mappings:
#     1: 43
#     2: 45
#     3: 47
#     4: 48
#     5: 50
#     6: 52
#     7: 53
#     8: 54
#     9: 55
#     10: 57
#     11: 59
#     12: 60
#     13: 61
#     14: 62
#     15: 63
#     16: 64
#     17: 65
#     18: 66
#     19: 67
#     20: 68
#     21: 69
#     22: 70
#     23: 71
#     24: 72
#     25: 73
#     26: 74
#     27: 75
#     28: 76
#     29: 77
#     30: 78
#     31: 79
#     32: 80
#     33: 81
#     34: 82
#     35: 83
#     36: 84
# metal:
#   # Radius of the inner label, unit does not matter but has to match the one used for outer radius
#   inner_radius: 1.8
#   # Radius of the entire disc, outer border ~8.4
#   outer_radius: 8.8
#   # Number of beats the disc has
#   number_beats: 144
#   # Bandwidth used for meanshift clustering the tracks
#   bandwidth: 4
#   # How far to look around each pixel when finding connected components in the image
#   search_distance: 1
#   # Average width of each track as relative distance between center and outer border
#   track_width: 0.01190476
#   # Relative position of the innnermost track from center to outer border = dist_innermostpolygon / outer_border? 
#   first_track: 0.214
#   # Total number of tracks on the disc
#   n_tracks: 94
#   # Low threshold for canny algorithm
#   canny_low: 50
#   # High threshold
#   canny_high: 255
#   # Preprocessing parameters
#   thresh_binary: 200
#   erosion_kernel: 3
#   noise_kernel: 5
#   brightness: 20
#   # Mappings of tracks to midi codes
#   track_mappings:
#     1: 43
#     2: 45
#     3: 47
#     4: 48
#     5: 50
#     6: 52
#     7: 53
#     8: 54
#     9: 55
#     10: 57
#     11: 59
#     12: 60
#     13: 61
#     14: 62
#     15: 63
#     16: 64
#     17: 65
#     18: 66
#     19: 67
#     20: 68
#     21: 69
#     22: 70
#     23: 71
#     24: 72
#     25: 73
#     26: 74
#     27: 75
#     28: 76
#     29: 77
#     30: 78
#     31: 79
#     32: 80
#     33: 81
#     34: 82
#     35: 83
#     36: 84
#     37: 85
#     38: 85
#     39: 85
#     40: 85
#     41: 85
#     42: 85
#     43: 85
#     44: 85
#     45: 85
#     46: 85
#     47: 85
#     48: 85
#     49: 85
#     50: 85
#     51: 85
#     52: 85
#     53: 85
#     54: 85
#     55: 85
#     56: 85
#     57: 85
#     58: 85
#     59: 85
#     60: 85
#     61: 85
#     62: 85
#     63: 85
#     64: 85
#     65: 85
#     66: 85
#     67: 85
#     68: 85
#     69: 85
#     70: 85
#     71: 85
#     72: 85
#     73: 85
#     74: 85
#     75: 85
#     76: 85
#     77: 85
#     78: 85
#     79: 85
#     80: 85
#     81: 85
#     82: 85
#     83: 85
#     84: 85
#     85: 85
#     86: 85
#     87: 85
#     88: 85
#     89: 85
#     90: 85
#     91: 85
#     92: 85
#     93: 85
#     94: 85
