methods:
  preprocessing.binarization:
    requires: []
    provides:
      - binarization
    suggests: []
    parameters:
      - bin_threshold
  preprocessing.edge_in:
    requires:
      - binarization
    provides:
      - edges
    suggests: []
    parameters: []
  preprocessing.crop_to_contents:
    requires:
      - binarization
    provides: []
    suggests: []
    parameters: []
  image.center_mean:
    requires: []
    provides:
      - center
    suggests:
      - binarization
    parameters: []
  image.center_iterative:
    requires:
      - center
    provides:
      - center
    suggests: []
    parameters:
      - angle
      - iterations
  image.labeling:
    requires:
      - edges
    provides:
      - labels
    suggests:
      - binarization
    parameters:
      - label_distance
  image.extract_shapes:
    requires:
      - labels
    provides:
      - shapes
    suggests: []
    parameters: []
  shapes.find_disc_edges:
    requires:
      - shapes
      - center
    provides:
      - disc_edge
      - label_edge
    suggests: []
    parameters:
      - inner_radius
      - outer_radius
  shapes.filter_inner:
    requires:
      - shapes
      - center
      - disc_edge
      - label_edge
    provides: []
    suggests: []
    parameters: 
      - inner_radius
      - outer_radius
  shapes.filter_size:
    requires:
      - shapes
    provides: []
    suggests: []
    parameters: []
  tracks.mean_shift:
    requires:
      - shapes
      - center
      - disc_edge
      - label_edge
    provides:
      - tracks
    suggests: []
    parameters:
      - bandwidth
  tracks.correct_empty:
    requires:
      - tracks
      - center
      - disc_edge
      - label_edge
    provides: []
    suggests: []
    parameters:
      - track_width
      - first_track
      - n_tracks
  notes.create_notes:
    requires:
      - tracks
      - center
    provides:
      - notes
    suggests: []
    parameters: []
  notes.find_beat_length:
    requires:
      - notes
    provides:
      - beat_length
    suggests: []
    parameters: []
  notes.create_midi:
    requires:
      - notes
    provides:
      - midi
      - data_array
    suggests:
      - beat_length
    parameters:
      - track_mappings
      - bpm
  analysis.detect_key:
    requires:
      - midi
    provides:
      - key
    suggests: []
    parameters: []
  analysis.find_harmonies_bass:
    requires:
      - data_array
    provides: []
    suggests: []
    parameters:
      - bass_cutoff
  analysis.find_harmonies_seq:
    requires:
      - data_array
    provides: []
    suggests: []
    parameters:
      - lookahead
      - cutoff
  image.center_least_squares:
    requires: []
    provides:
      - center
    suggests:
      - binarization
    parameters: []
  image.extract_roll_notes:
    requires: 
      - shapes
      - roll_edges
    provides:
      - notes
    suggests: []
    parameters:
      - width
      - track_measurements
  helpers.enter_debug:
    requires: []
    provides: []
    suggests: []
    parameters: []
  image.classify_shapes:
    requires:
      - shapes
    provides: []
    suggests: []
    parameters: []
  preprocessing.trim_roll_ends:
    requires:
      - binarization
    provides: []
    suggests: []
    parameters: []
  notes.scale_fixed_factor:
    requires:
      - notes
    provides: []
    suggests: []
    parameters: 
      - dpi
      - feet_per_minute
  image.filter_roll_shapes:
    requires:
      - shapes
    provides: []
    suggests: []
    parameters: []
  image.find_roll_edges:
    requires:
      - shapes
    provides:
      - roll_edges
    suggests: []
    parameters: []
  image.center_manual:
    requires: []
    provides:
      - center
    suggests: []
    parameters:
      - center_manual_x
      - center_manual_y
  notes.merge_roll_notes:
    requires:
      - notes
    provides: []
    suggests: []
    parameters:
      - notes_per_second